# Comparison Class Inference Experiment Analysis

``` {r libraries}
library(tidyverse)
library(tidyboot)
library(brms)
library(lmerTest)
```

``` {r data}
# read data
d_infer <- read_csv('./data/results_30_prereg-cc-inf.csv')

```

``` {r filter}
# exclude participants who report difficulties
d_infer %>% select(submission_id, comments, problems) %>% distinct() %>% View()
d_infer_woGlitches <- subset(d_infer, !(submission_id %in% c(1438, 1515)))

# exclude data from non-native English speakers and those where the language information is missing
d_infer_woGlitches %>% distinct(languages)
d_infer_Native <- d_infer_woGlitches %>%
  filter(grepl("en", languages, ignore.case = T)) %>%
  select(submission_id, trial_name, trial_number, target_size, item, botresponse, response,
         condition,  pic, pic_spec, ref_spec, attempts)

# participants who do not get the comparison class warmup right
d_infer_cc_warmup <- d_infer_Native %>% filter( trial_name == "comp_class_warmup") %>%
  group_by(submission_id) %>% count() %>%
  filter( n > 4 )

# exclude participants who need more than 4 attempts per warmup
d_infer_warmup <- d_infer_Native %>%
  filter( (trial_name == "warmup1") | (trial_name == "warmup2")) %>%
  group_by(submission_id) %>%
  filter(attempts > 4)

d_infer_filt1 <- anti_join(d_infer_Native, d_infer_warmup, by = c("submission_id"))
d_infer_filt1 <- anti_join(d_infer_filt1, d_infer_cc_warmup, by = c("submission_id"))
```

``` {r csv vars}
# write a csv with subject exclusion stats for TeX
myvars = list()

myvars["nSubj"] = (d_infer %>% distinct(submission_id) %>% count() %>% .$n) - 2   # one extra participant was collected, excluded below
myvars["nExcludedTotal"] = ((d_infer %>% distinct(submission_id) %>% count() %>% .$n) ) -
  (d_infer_filt1 %>% distinct(submission_id) %>% count() %>% .$n)
myvars["nBugs"] = 0 # subject excluded due to glitches
myvars["nNonEN"] = (d_infer_woGlitches %>% distinct(submission_id) %>% count() %>% .$n) -
  (d_infer_Native %>% distinct(submission_id) %>% count() %>% .$n)
myvars["nFailedWarmUp"] = (d_infer_warmup %>% distinct(submission_id) %>% count() %>% .$n %>% sum())
myvars["nFailedCCWarmUp"] = d_infer_cc_warmup %>% distinct(submission_id) %>% count() %>% .$n %>% sum()
#myvars["nFailedMains"] = d_catch_main_counts %>% distinct(submission_id) %>% count() %>% .$n

myvars = as_tibble(myvars)
#write_csv(myvars, path = "R_results_TeX/myvars-infer.csv", col_names = T)
```



``` {r categorization}
d_infer_main <- d_infer_filt1 %>% filter((trial_name == "custom_main_text1")|
                                          (trial_name == "custom_main_text2")) %>%
  filter(submission_id != 1548) %>% filter(submission_id != 1549) %>%
  mutate(context = factor(pic_spec, levels = c(0, 1),
                          labels = c("basic",
                                     "subordinate")),
         NP = ifelse(ref_spec == 2, "one",
                     ifelse(ref_spec == 1, "subordinate", "basic")),
         condition = ifelse(condition == 0, "prenominal", "predicative")) %>%
  select(submission_id, trial_number, context, item, response, condition,
        pic, target_size, NP)

# categorize responses
d_infer_main %>% distinct(response) %>% View()
# exclude invalid responses
d_infer_valid <- d_infer_main %>% subset(., !(tolower(response) %in% c("that man is big", "that's small boy", "that is big one", "that's a small doberman",
                                                                      "that bird compare small", "that boy is small", "me is big", "but some one small", "that pug small",
                                                                      "you are small", "beauty for fish", "yes", "aim", "growth", "honest", "medicine", "heathy", "dogs name", "trees name",
                                                                      "big", "tall", "small", "cute", "good", "bushes",
                                                                      "why it in land", "what is this flower", "fish nose", "labrador")))
d_infer_main_responseCat <- d_infer_valid %>%
  rowwise() %>%
  mutate(  
    response_cat =
      ifelse( # do be extended dependent on responses provided
        tolower(response) %in% c("birds", "bird", "dogs", "fish", "flowers", "birds in the sky", "big dogs", "fower", "tress", "things", "objects", "dogs.", "dogd",
                                 "burds", "dogs that we see", "fish that we see", "birds that we see",
                                 "flower", "trees","tree", "animal", "the other birds", "the other dogs", "digs", "treees", "weeds", "small flowers", "fishs",
                                 "fishes", "dog", "large dogs", "giant trees", "breeds", "plant", "variety of dogs", "long trees"), "basic", "subordinate"),

    response_num = ifelse(response_cat == "basic", 1, 0),
    response_label = "basic"
  )
d_infer_main_superordinate <- d_infer_main_responseCat %>%
  filter(tolower(response) %in% c("things", "objects", "animal", "weeds", "plant"))
```


``` {r proportions plot}
# plot
bar.width = 0.8
d_infer_main_responseCat %>%  
  group_by( context, NP, condition) %>%
  tidyboot_mean(column = response_num) -> d_infer_main_responseCat.bs


d_infer_main_responseCat.bs %>%
  ungroup() %>%
  mutate(condition = factor(condition, levels = c( "predicative", "prenominal"),
                            labels = c(  "Subject NP\n(That NP is big)", "Predicate NP\n(That's a big NP)")),
         context = factor(context, levels = c("basic", "subordinate"),
                          labels = c("Basic-Level Context","Subordinate-Level Context")),
         NP = factor(NP, levels = c("basic", "one", "subordinate"),
                     labels = c("basic", '"one"', "subordinate"))) %>%
  ggplot(., aes(x=condition, y = mean, fill = NP, ymin = ci_lower, ymax = ci_upper)) +
  geom_col(position = position_dodge(bar.width), width = bar.width, color= 'black',
           alpha = 0.5, color = 'black', size = 1) +
  geom_linerange(position = position_dodge(bar.width), size = 1) +
  ggthemes::theme_few()+
  xlab("") +
  theme(legend.position = c(0.88, 0.84),#legend.text = element_text(size = 7),
        #legend.title = element_text(size = 7), 
        legend.key.size = unit(0.5,"line"))+
  scale_y_continuous(breaks = c(0, 0.5, 1))+
  ylab("Proportion of basic-level responses")+
 # ggtitle("Experiment 3: Comparison Class Inference")+
  facet_grid(~context)  +
  ggsave("figs/expt3-cc-inference.pdf", width = 7.5, height = 3.5)
```


``` {r}
# explicit numeric coding to improve model convergence
d_infer_main_responseCat <- d_infer_main_responseCat %>%
  mutate(syntax_contr = ifelse(condition == "predicative", 0.5, -0.5), # contrast coded
         NP_basic = ifelse(NP == "basic", 1, 0), # treatment coded
         NP_sub = ifelse(NP == "subordinate", 1, 0),
         context_sub = ifelse(context == "subordinate", 1, 0))


contrasts(d_infer_main_responseCat$NP_sub)

d_infer_main_responseCat2 <- d_infer_main_responseCat %>%
  ungroup() %>%
  mutate(NP_fac = factor(as.character(NP)),
         NP_num = as.numeric(NP_fac)) %>%
  mutate(syntax_contr = ifelse(condition == "predicative", 0.5, -0.5), # contrast coded
         context_sub = ifelse(context == "subordinate", 0.5,-0.5)) %>%
  rowwise() %>%
  mutate(NP_subVone = case_when(NP == "one" ~ -1L, # baseline
                        NP == "subordinate" ~ 1L,  # target
                        TRUE      ~ 0L), # anything else
        NP_basicVone = case_when(NP == "one" ~ -1L, # baseline
                        NP == "basic" ~  1L, # target
                        TRUE      ~ 0L),
        syntax_sum = ifelse(condition == "predicative", -1L, 1L),
        context_sum = ifelse(context == "basic", -1L, 1L))

d_infer_main_responseCat2 %>%
  select(condition, syntax_sum, context, context_sum, NP, NP_OneVsub, NP_basicVsub) %>%
  View()
# 
#   mutate(
#     NP_sub1 = contr.sum(3)[NP_num,][1],
#     NP_sub2 = contr.sum(3)[NP_num,][2]
#     )

rs.glm <- glm(response_num~syntax_contr * (NP_sub1 + NP_sub2) * context_sub,
    data = d_infer_main_responseCat2,
    family = 'binomial')

summary(rs.glm)

rs.glm0 <- glm(response_num~syntax_contr * (NP_sub1 + NP_sub2) * context_sub - (NP_sub1 + NP_sub2) : syntax_contr,
    data = d_infer_main_responseCat2,
    family = 'binomial')

summary(rs.glm)

anova(rs.glm0,rs.glm,test="Chisq")

rs.glm.noint <- glm(response_num~syntax_contr * (NP_sub1 + NP_sub2) * context_sub - syntax_contr : (NP_sub1 + NP_sub2) : context_sub,
    data = d_infer_main_responseCat2,
    family = 'binomial')

anova(rs.glm.noint,rs.glm,test="Chisq")
```

```{r}
rs.glmer <- glmer(response_num~syntax_sum * (NP_OneVsub + NP_basicVsub) * context_sum + 
                    (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) * context_sum || submission_id)  + 
                    (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) * context_sum || item),
    data = d_infer_main_responseCat2, 
    family = 'binomial',
    control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)))

summary(rs.glmer)
```


```{r}
rs.glmer.basicContext <- glmer(response_num~syntax_sum * (NP_OneVsub + NP_basicVsub) + 
                    (1 | submission_id)  + 
                    (1 | item),
                    # (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) || submission_id)  + 
                    # (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) || item),
    data = d_infer_main_responseCat2 %>% 
      filter(context == "basic"), 
    family = 'binomial')
  #  control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))


rs.glmer.basicContext.summary <- summary(rs.glmer.basicContext)

rs.glmer.basicContext.summary$varcor
```

```{r}
rs.glmer.basicContext.noOne <- glmer(response_num~syntax_sum * NP_basicVsub + 
                    (1 | submission_id)  + 
                    (1 | item),
                    # (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) || submission_id)  + 
                    # (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) || item),
    data = d_infer_main_responseCat2 %>% 
      filter(context == "basic", NP != "one"), 
    family = 'binomial')
  #  control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

rs.glmer.subContext.noOne <- glmer(response_num~syntax_sum * NP_basicVsub + 
                    (1 | submission_id),
                    #(1 | item),
                    # (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) || submission_id)  + 
                    # (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) || item),
    data = d_infer_main_responseCat2 %>% 
      filter(context == "subordinate", NP != "one"), 
    family = 'binomial')
  #  control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))


rs.glmer.basicContext.noOne.summary <- summary(rs.glmer.basicContext.noOne)

summary(rs.glmer.subContext.noOne)
```


``` {r lmer}
# random effects correlation must be set to 0 to estimate the model
# significant effect of context and sub NP
lm.infer.fit <- glmer(response_num ~ syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        context_sub:NP_basic + context_sub:NP_sub +
                        syntax_contr:context_sub +
                        syntax_contr:NP_basic:context_sub +
                        syntax_contr:NP_sub:context_sub +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        context_sub:NP_basic + context_sub:NP_sub +
                        syntax_contr:context_sub +
                        syntax_contr:NP_basic:context_sub +
                        syntax_contr:NP_sub:context_sub || submission_id) +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        context_sub:NP_basic + context_sub:NP_sub +
                        syntax_contr:context_sub +
                        syntax_contr:NP_basic:context_sub +
                        syntax_contr:NP_sub:context_sub || item),
                      data = d_infer_main_responseCat,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                  )
summary(lm.infer.fit) # full model

```

``` {r brm model}
# Bayesian full model
# significant effect of sub NP and context
lm.b.infer.fit.by.target <- brm(response_num ~ syntax_sum * (NP_OneVsub + NP_basicVsub) * context_sum +
                        (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) * context_sum  || submission_id) +
                        (1 + syntax_sum * (NP_OneVsub + NP_basicVsub) * context_sum  || pic),
                      data = d_infer_main_responseCat2,
                      family = "bernoulli",
                      iter = 1000,
                      cores = 3, chains = 3,
                      control = list(adapt_delta = 0.9)) # otherwise there are divergent chains




coda = brms::posterior_samples(lm.b.infer.fit.by.target)
antilogit = function(x) 1 / (1 + exp(-x))


lm.b.infer3way.by.target.fit.samples <- data.frame(
  basic_v_mean = coda[,"b_NP_basicVsub"],
  one_v_mean = coda[,"b_NP_OneVsub"],
  syntax_one_v_mean = coda[, "b_syntax_sum:NP_OneVsub"],
  syntax_basic_v_mean = coda[, "b_syntax_sum:NP_basicVsub"],
  syntax_context_one_v_mean = coda[, "b_syntax_sum:NP_OneVsub:context_sum"],
  syntax_context_basic_v_mean = coda[, "b_syntax_sum:NP_basicVsub:context_sum"]
) %>%
  mutate(
    one_v_sub = 2 * one_v_mean + basic_v_mean,
    one_v_basic = one_v_mean - basic_v_mean,
    basic_v_sub = 2* basic_v_mean + one_v_mean,
    syntax_one_v_sub = 2 *syntax_one_v_mean + syntax_basic_v_mean,
   syntax_one_v_basic = syntax_one_v_mean - syntax_basic_v_mean,
   syntax_basic_v_sub = 2 * syntax_basic_v_mean + syntax_one_v_mean,
   context_syntax_one_v_sub = 2 *syntax_context_one_v_mean + syntax_context_basic_v_mean,
   context_syntax_one_v_basic = syntax_context_one_v_mean - syntax_context_basic_v_mean,
   context_syntax_basic_v_sub = 2 * syntax_context_basic_v_mean + syntax_context_one_v_mean,
     )


lm.b.infer3way.by.target.fit.samples %>%
  gather(key, val) %>%
  ggplot(., aes( x= val))+
  geom_histogram()+
  facet_wrap(~key)

mean(lm.b.infer3way.by.target.fit.samples$one_v_sub)
quantile(lm.b.infer3way.by.target.fit.samples$one_v_sub, probs = c(0.025, 0.975))
mean(lm.b.infer3way.by.target.fit.samples$one_v_basic)
quantile(lm.b.infer3way.by.target.fit.samples$one_v_basic, probs = c(0.025, 0.975))
quantile(lm.b.infer3way.by.target.fit.samples$basic_v_sub, probs = c(0.025, 0.975))


quantile(lm.b.infer3way.by.target.fit.samples$syntax_one_v_sub, probs = c(0.025, 0.975))
quantile(lm.b.infer3way.by.target.fit.samples$syntax_one_v_basic, probs = c(0.025, 0.975))

mean(lm.b.infer3way.by.target.fit.samples$syntax_basic_v_sub)
quantile(lm.b.infer3way.by.target.fit.samples$syntax_basic_v_sub, probs = c(0.025, 0.975))
mean(lm.b.infer3way.by.target.fit.samples$syntax_basic_v_sub < 0)


quantile(lm.b.infer3way.by.target.fit.samples$context_syntax_one_v_sub, probs = c(0.025, 0.975))
quantile(lm.b.infer3way.by.target.fit.samples$context_syntax_one_v_basic, probs = c(0.025, 0.975))
quantile(lm.b.infer3way.by.target.fit.samples$context_syntax_basic_v_sub, probs = c(0.025, 0.975))
```

``` {r brm csv}
myTable_infer = cbind(tibble(Rowname = row.names(summary(lm.b.infer.fit.by.target)[["fixed"]])),
                summary(lm.b.infer.fit.by.target)[["fixed"]] %>% as_tibble())
write_csv(myTable_infer, path = "R_results_TeX/cc-infer-brm.csv", col_names = T)
lm.b.infer.summary <- summary(lm.b.infer.fit.by.target)
write_csv(data.frame(lm.b.infer.summary[["fixed"]]) %>%
            mutate(Rowname = row.names(.)),
          path = "R_results_TeX/expt3_brm.csv")

```


``` {r by-size}
d_infer_main_responseCat %>%  
  group_by( context, NP, condition, target_size) %>%
  tidyboot_mean(column = response_num) -> d_infer_main_responseCat.by.size

d_infer_main_responseCat.by.size %>%
  ungroup() %>%
  mutate(condition = factor(condition, levels = c( "predicative", "prenominal"),
                            labels = c(  "Subject NP\n(That NP is big)", "Predicate NP\n(That's a big NP)")),
         context = factor(context, levels = c("basic", "subordinate"),
                          labels = c("Basic-Level Context","Subordinate-Level Context")),
         NP = factor(NP, levels = c("basic", "one", "subordinate"),
                     labels = c("basic", '"one"', "subordinate"))) %>%
  ggplot(., aes(x=condition, y = mean, fill = NP, ymin = ci_lower, ymax = ci_upper)) +
  geom_col(position = position_dodge(bar.width), width = bar.width, color= 'black',
           alpha = 0.5, color = 'black', size = 1) +
  geom_linerange(position = position_dodge(bar.width), size = 1) +
  ggthemes::theme_few()+
  xlab("") +
  ylab("Proportion of basic-level responses")+
 # ggtitle("Experiment 3: Comparison Class Inference")+
  facet_grid(target_size~context)  +
 ggsave("figs/expt-cc-infer-by-size.png", width = 7.5, height = 3.5)
```

```{r}
# two-way analysis
lm.b.infer.fit.two.way3 <- brm(response_num ~ syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || submission_id) +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || item),
                      data = d_infer_main_responseCat,
                      family = "bernoulli",
                      iter = 1500,
                      cores = 4,
                      control = list(adapt_delta = 0.9))


NP_basicVone
NP_subVone

lm.b.infer.fit.two.way2.sum <- brm(response_num ~ syntax_sum + NP_subVone + NP_basicVone + context_sum  +
                        syntax_sum:NP_subVone + syntax_sum:NP_basicVone +
                        (1 + syntax_sum + NP_subVone + NP_basicVone + context_sum  +
                        syntax_sum:NP_subVone + syntax_sum:NP_basicVone || submission_id) +
                        (1 + syntax_sum + NP_subVone + NP_basicVone + context_sum  +
                        syntax_sum:NP_subVone + syntax_sum:NP_basicVone || item),
                      data = d_infer_main_responseCat2,
                      family = "bernoulli",
                      iter = 1500,
                      cores = 4,
                      control = list(adapt_delta = 0.9))

coda = brms::posterior_samples(lm.b.infer.fit.two.way2.sum)

lm.b.infer.fit.samples <- data.frame(
  sub_v_mean = coda[, "b_syntax_sum:NP_subVone"],
  basic_v_mean = coda[, "b_syntax_sum:NP_basicVone"]
) %>%
  mutate(sub_v_one = 2 *sub_v_mean + basic_v_mean,
         sub_v_basic = sub_v_mean - basic_v_mean,
         basic_v_one = 2 * basic_v_mean + sub_v_mean)


lm.b.infer.fit.samples %>%
  gather(key, val) %>%
  ggplot(., aes( x= val))+
  geom_histogram()+
  facet_wrap(~key)

mean(lm.b.infer.fit.samples$sub_v_one)
quantile(lm.b.infer.fit.samples$sub_v_one, probs = c(0.025, 0.975))

mean(lm.b.infer.fit.samples$sub_v_one<0)


mean(lm.b.infer.fit.samples$sub_v_basic)
quantile(lm.b.infer.fit.samples$sub_v_basic, probs = c(0.025, 0.975))
mean(lm.b.infer.fit.samples$basic_v_one)
quantile(lm.b.infer.fit.samples$basic_v_one, probs = c(0.025, 0.975))
mean(lm.b.infer.fit.samples$basic_v_one>0)

```


```{r}

# two-way analysis
lm.b.infer.fit.two.way2.item <- brm(response_num ~ syntax_sum + NP_OneVsub + NP_basicVsub + context_sum  +
                        syntax_sum:NP_OneVsub + syntax_sum:NP_basicVsub +
                        (1 + syntax_sum + NP_OneVsub + NP_basicVsub + context_sum  +
                        syntax_sum:NP_OneVsub +  syntax_sum:NP_basicVsub || submission_id) +
                        (1 + syntax_sum + NP_OneVsub + NP_basicVsub + context_sum  +
                        syntax_sum:NP_OneVsub + syntax_sum:NP_basicVsub || item),
                      data = d_infer_main_responseCat2,
                      family = "bernoulli",
                      iter = 1500,
                      cores = 4,
                      control = list(adapt_delta = 0.98)) # otherwise there are divergent chains

summary(lm.b.infer.fit.two.way) # 1000 iterations and by-target radom effects

lm.b.infer.fit.two.way.by.item.summary <- summary(lm.b.infer.fit.two.way2)
lm.b.infer.fit.two.way3.summary <- summary(lm.b.infer.fit.two.way3)
write_csv(data.frame(lm.b.infer.fit.two.way3.summary[["fixed"]]) %>%
            mutate(Rowname = row.names(.)),
          path = "R_results_TeX/expt3_2_way_full_brm.csv")
```


``` {r csv}
write_csv(data.frame(lm.b.infer.fit.two.way.by.item.summary[["fixed"]]) %>%
            mutate(Rowname = row.names(.)),
          path = "R_results_TeX/expt3_2_way_brm.csv")
```

``` {r}
d_infer_main_responseCat <- d_main_responseCat %>%
  mutate(syntax_sum = ifelse(syntax == "subject", 0, 1),
         NP_sum = ifelse(NP == "basic", 0, 1),
         context_sum = ifelse(context == "basic", 0, 1))
```

``` {r by-size}
d_infer_big <- d_infer_main_responseCat %>% filter(target_size == "big")
d_infer_small <- d_infer_main_responseCat %>% filter(target_size == "small")
lm.b.infer.big <- brm(response_num ~ syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        context_sub:NP_basic + context_sub:NP_sub +
                        syntax_contr:context_sub +
                        syntax_contr:NP_basic:context_sub +
                        syntax_contr:NP_sub:context_sub +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        context_sub:NP_basic + context_sub:NP_sub +
                        syntax_contr:context_sub +
                        syntax_contr:NP_basic:context_sub +
                        syntax_contr:NP_sub:context_sub || submission_id) +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        context_sub:NP_basic + context_sub:NP_sub +
                        syntax_contr:context_sub +
                        syntax_contr:NP_basic:context_sub +
                        syntax_contr:NP_sub:context_sub || pic),
                      data = d_infer_big,
                      family = "bernoulli",
                      iter = 1000,
                      cores = 4,
                      control = list(adapt_delta = 0.9))
summary(lm.b.infer.big)
```

``` {r by-context and size}
# GIVEN plot above, analysis of small targets in basic level context 
d_infer_basicContext_small <- d_infer_main_responseCat %>% filter((target_size == "small") & (context == "basic"))
lm.infer.basicC.small <- glmer(response_num ~ syntax_contr + NP_basic + NP_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        (0 + #syntax_contr + NP_basic + NP_sub + 
                       # syntax_contr:NP_basic + 
                          syntax_contr:NP_sub  || submission_id) +
                        (0 + #syntax_contr + NP_basic + NP_sub + 
                        #syntax_contr:NP_basic + 
                          syntax_contr:NP_sub || item),
                      data = d_infer_basicContext_small,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                  )
d_infer_basicContext_small.summary <- summary(lm.infer.basicC.small)
d_infer_basicContext_small_sub <- d_infer_basicContext_small %>% filter(NP == "subordinate")
lm.infer.basicC.small.sub <- glmer(response_num ~ syntax_contr +(0 + syntax_contr || submission_id) +
                                     (1 + syntax_contr | pic),
                                   data = d_infer_basicContext_small_sub,
                                   family = "binomial",
                                   control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                            )
lm.infer.basicC.small.sub.summary <- summary(lm.infer.basicC.small.sub)
```


Assuming NO interaction with context

```{r}

b.infer.noContextInt <- brm(response_num ~ syntax_contr + NP_basic + NP_sub +
                                     context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || submission_id) +
                        (1 + syntax_contr + NP_basic + NP_sub + context_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || item),
                      data = d_infer_main_responseCat,
                      chains = 3, cores = 3, iter = 1000,
                      family = "bernoulli",
                      control = list(adapt_delta = 0.92))
summary(b.infer.noContextInt)
```



``` {r}
# secondary analysis
# subsetting the data by context condition
d_infer_contextBasic <- d_infer_main_responseCat %>%
  filter(context == "basic")
d_infer_contextSub <- d_infer_main_responseCat %>%
  filter(context == "subordinate")

# lmer analysis
# does not converge
lm.infer.context.basic <- glmer(response_num ~ syntax_contr + NP_basic + NP_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        (1 | submission_id) +  #syntax_contr + NP_basic + NP_sub +
                      #  syntax_contr:NP_basic + syntax_contr:NP_sub || submission_id) +
                        (0 + #syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || item),
                      data = d_infer_contextBasic,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
# converges
lm.infer.context.sub <- glmer(response_num ~ syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        (1 + syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || submission_id) +
                        (1 + syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || item),
                        data = d_infer_contextSub,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
summary(lm.infer.context.basic)
summary(lm.infer.context.sub)

# bayesian models of separate contexts
# basic context
b.context.basic <- brm(response_num ~ syntax_contr + NP_basic + NP_sub  +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        (1 + syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || submission_id) +
                        (1 + syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || item),
                      data = d_infer_contextBasic,
                      family = "bernoulli",
                      iter = 1000,
                      chains = 3,
                      cores = 3)
summary(b.context.basic)

# sub context
b.context.sub <- brm(response_num ~ syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub +
                        (1 + syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || submission_id) +
                        (1 + syntax_contr + NP_basic + NP_sub +
                        syntax_contr:NP_basic + syntax_contr:NP_sub || item),
                        data = d_infer_contextSub,
                      family = "bernoulli",
                     cores = 4)

summary(b.context.sub)
```



``` {r}
# basic context, subset by NP
d_infer_contextBasic_sub <- d_infer_contextBasic %>%
  filter(NP == "subordinate")
d_infer_contextBasic_basic <- d_infer_contextBasic %>%
  filter(NP == "basic")
d_infer_contextBasic_one <- d_infer_contextBasic %>%
  filter(NP == "one")

# these model should all run
lm.basic.sub <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_infer_contextBasic_sub,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.basic.basic <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_infer_contextBasic_basic,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.basic.one <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_infer_contextBasic_one,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
summary(lm.basic.sub)
```

``` {r}
# subordinate context, subset by NP
d_infer_contextSub_sub <- d_infer_contextSub %>%
  filter(NP == "subordinate")
d_infer_contextSub_basic <- d_infer_contextSub %>%
  filter(NP = "basic")
d_infer_contextSub_one <- d_infer_contextSub %>%
  filter(NP == "one")

lm.sub.sub <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_infer_contextSub_sub,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.sub.basic <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_infer_contextSub_basic,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.sub.one <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_infer_contextSub_one,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
```

``` {r}
# secondary analysis without the NP 'one'
d_infer_subsetNP <- d_infer_main_responseCat %>%
  filter(NP != "one")
d_infer_subsetNP <- d_infer_subsetNP %>%
  mutate(NP_treatment = ifelse(NP == "subordinate", 1, 0)) # NP treatment coded, basic level - reference level

# model cannot be estimated with correlating random effects
# converges, significant effect of sub NP and sub context
lm.infer.subset <- glmer(response_num ~ syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment +
                        context_sub:NP_treatment +
                        syntax_contr:context_sub +
                        (1 + syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment +
                        context_sub:NP_treatment +
                        syntax_contr:context_sub +
                        syntax_contr:NP_treatment:context_sub || submission_id) +
                        (1 + syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment +
                        context_sub:NP_treatment +
                        syntax_contr:context_sub +
                        syntax_contr:NP_treatment:context_sub  || item),
                      data = d_infer_subsetNP,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
summary(lm.infer.subset)

lm.infer.subset.summary <- summary(lm.infer.subset)
write_csv(data.frame(lm.infer.subset.summary[["coefficients"]]) %>%
            mutate(Rowname = row.names(.)),
          path = "R_results_TeX/expt3_wo_one_3_way_lmer.csv")

# bayesian full model without 'one'

b.infer.subset <- brm(response_num ~ syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment +
                        context_sub:NP_treatment +
                        syntax_contr:context_sub +
                        syntax_contr:NP_treatment:context_sub +
                        (1 + syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment +
                        context_sub:NP_treatment +
                        syntax_contr:context_sub +
                        syntax_contr:NP_treatment:context_sub || submission_id) +
                        (1 + syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment +
                        context_sub:NP_treatment +
                        syntax_contr:context_sub +
                        syntax_contr:NP_treatment:context_sub  || item),
                      data = d_infer_subsetNP,
                      family = "bernoulli",
                      chains = 3, cores = 3, iter = 1000,
                      control = list(adapt_delta = 0.9))
summary(b.infer.subset)
```


``` {r}
# subset by syntactic condition within context to test effect of NP
d_infer_contextBasic_subject <- d_infer_contextBasic %>% filter(condition == 'predicative')
lm.infer.basicContext.subj <- glmer(response_num ~ NP_basic + NP_sub + 
                                      (0 + NP_sub + NP_basic || submission_id) +
                                      (0 + NP_sub + NP_basic || item),
                                    data = d_infer_contextBasic_subject,
                                    family = 'binomial',
                                    REML = F,
                                    control=glmerControl(optimizer="bobyqa",
                                                         optCtrl=list(maxfun=2e5)))
summary(lm.infer.basicContext.subj)
```


Assuming NO interaction with context

```{r}
# bayesian full model without 'one'

b.infer.subset.noContextInt <- brm(response_num ~ syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment +
                        (1 + syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment || submission_id) +
                        (1 + syntax_contr + NP_treatment + context_sub  +
                        syntax_contr:NP_treatment || item),
                      data = d_infer_subsetNP,
                      chains = 3, cores = 3, iter = 1000,
                      family = "bernoulli",
                      control = list(adapt_delta = 0.9))
summary(b.infer.subset.noContextInt)
```



``` {r}

# subset by context
d_subset_contextBasic <- d_infer_subsetNP %>%
  filter(context == "basic")
d_subset_contextSub <- d_infer_subsetNP %>%
  filter(context == "subordinate")

# full model does not converge, random effects must be set to 0  
# significant effect of NP
lm.subset.context.basic <- glmer(response_num ~ syntax_contr + NP_treatment  +
                        syntax_contr:NP_treatment +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || submission_id) +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || item),
                      data = d_subset_contextBasic,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.subset.context.basic.summary <- summary(lm.subset.context.basic)
write_csv(data.frame(lm.subset.context.basic.summary[["coefficients"]]) %>%
            mutate(Rowname = row.names(.)),
          path = "R_results_TeX/expt3_wo_one_basicContext.csv")

# converges, significant effect of NP
lm.subset.context.sub <- glmer(response_num ~ syntax_contr + NP_treatment  +
                        syntax_contr:NP_treatment +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || submission_id) +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || item),
                      data = d_subset_contextSub,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )

lm.subset.context.sub.summary <- summary(lm.subset.context.sub)
write_csv(data.frame(lm.subset.context.sub.summary[["coefficients"]]) %>%
            mutate(Rowname = row.names(.)),
          path = "R_results_TeX/expt3_wo_one_subContext.csv")
# bayesian model of sub context without 'one'
b.subset.context.sub <- brm(response_num ~ syntax_contr + NP_treatment  +
                        syntax_contr:NP_treatment +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || submission_id) +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || item),
                      data = d_subset_contextSub,
                      family = "bernoulli",
                      cores = 3, chains = 3, iter = 1000)
summary(b.subset.context.sub)
# bayesian model of basic context without 'one'
b.subset.context.basic <- brm(response_num ~ syntax_contr + NP_treatment  +
                        syntax_contr:NP_treatment +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || submission_id) +
                        (1 + syntax_contr + NP_treatment +
                        syntax_contr:NP_treatment || item),
                      data = d_subset_contextBasic,
                      family = "bernoulli",
                      cores = 3, chains = 3, iter = 1000)
summary(b.subset.context.basic)
```

``` {r}

# subset by NP
d_subset_contextSub_sub <- d_subset_contextSub %>%
  filter(NP == "subordinate")
d_subset_contextSub_basic <- d_subset_contextSub %>%
  filter(NP = "basic")
d_subset_contextSub_one <- d_subset_contextSub %>%
  filter(NP == "one")

# these models should run
lm.subset.sub.sub <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_subset_contextSub_sub,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.subset.sub.basic <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_subset_contextSub_basic,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.subset.sub.one <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_subset_contextSub_one,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
# basic context
d_subset_contextBasic_sub <- d_subset_contextBasic %>%
  filter(NP == "subordinate")
d_subset_contextBasic_basic <- d_subset_contextBasic %>%
  filter(NP = "basic")
d_subset_contextBasic_one <- d_subset_contextBasic %>%
  filter(NP == "one")

lm.subset.basic.sub <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_subset_contextBasic_sub,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.subset.basic.basic <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_subset_contextBasic_basic,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
lm.subset.basic.one <- glmer(response_num ~ syntax_contr +
                        (1 + syntax_contr | submission_id)+
                        (1 + syntax_contr | item),
                      data = d_subset_contextBasic_one,
                      family = "binomial",
                      REML = F,
                      control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                      )
```


MH playing around

```{r}
d_infer_subsetNP.fctrs <- d_infer_subsetNP %>%
  ungroup() %>%
  mutate(NP = factor(NP),
         condition = factor(condition))

contrasts(d_infer_subsetNP.fctrs$context)
contrasts(d_infer_subsetNP.fctrs$NP) #<- c(-0.5, 0.5)
contrasts(d_infer_subsetNP.fctrs$condition) <- c(-0.5, 0.5)

lm.infer.subset <- glmer(response_num ~ context * NP * condition +
                           (1  | submission_id),
                         family = "binomial",
                        data = d_infer_subsetNP.fctrs)

glm.infer.subset <- glm(response_num ~ context * NP * condition,
                         family = "binomial",
                        data = d_infer_subsetNP.fctrs)
```


```{r}
glm.infer.subset.basicContext <- glm(response_num ~ NP * condition,
                         family = "binomial",
                        data = d_infer_subsetNP.fctrs %>%
                          filter(context == "basic"))

summary(glm.infer.subset.basicContext)

d_infer_subsetNP.fctrs %>%
  filter(context == "basic") %>%
  group_by(NP, condition) %>%
  summarize(m = mean(response_num))
```

```{r}
glm.infer.subset.subContext <- glm(response_num ~ NP * condition,
                         family = "binomial",
                        data = d_infer_subsetNP.fctrs %>%
                          filter(context == "subordinate"))

summary(glm.infer.subset.subContext)
```

```{r}
glm.infer.subset.mainContext <- glm(response_num ~  context + NP * condition,
                         family = "binomial",
                        data = d_infer_subsetNP.fctrs)

glmer.infer.subset.mainContext <- glmer(response_num ~ context + NP * condition  +
                                        ( 1 + condition | submission_id) +
                                        ( 1 + condition | item),
                         family = "binomial",
                        data = d_infer_subsetNP.fctrs)

summary(glmer.infer.subset.mainContext)
```
