# NP production experiment analysis

``` {r}
# libraries
library(tidyverse)
library(tidyboot)
library(brms)
library(lmerTest)
```

``` {r}
# read the data
d_prod <- rbind( rbind(read_csv('./data/results_8_exp1-post-prereg-pred.csv'),
                       read_csv('./data/results_8_exp1-post-prereg-pred_batch2.csv')), 
                  rbind(read_csv('./data/results_10_exp1-post-prereg-prenom.csv'),
                        read_csv('./data/results_10_exp1-post-prereg-prenom_batch2.csv')
                        )) 
```

``` {r}
# exclude participants who report difficulties 
d_prod %>% select(submission_id, comments, problems) %>% distinct() %>% View()
# d_prod <- subset(d_prod, !(submission_id %in% c(....)))

# exclude data from non-native English speakers and those where the language information is missing
d_prod %>% distinct(languages)
d_prod_filt <- d_prod %>% 
  filter(grepl("eng", languages, ignore.case = T)) %>%
  select(submission_id, trial_name, trial_number, attempts, size, item, botresponse, response,
         condition,  picture, target) %>% 
  mutate(size = factor(size), syntax = factor(condition))

# get participants who need more than 4 attempts per warmup
d_prod_warmup <- d_prod_filt %>% 
  filter( (trial_name == "warmup1") | (trial_name == "warmup2"))
d_prod_warmup <- d_prod_warmup %>% group_by(submission_id) %>% 
  filter( attempts > 4)
# exclude those participants
d_prod_filt <- anti_join(d_prod_filt, d_prod_warmup, by = c("submission_id"))
``` 

```{r}
# main trials 
d_prod_main <- d_prod_filt %>% filter((trial_name == "main1") | (trial_name == "main2")) %>%
  select(submission_id, trial_number, trial_name, response, size, item, syntax, picture, target)

# look at the responses
d_prod_main %>% distinct(response) %>% View()
# exlclude invalid responses 
d_prod_main_valid <- subset(d_prod_main, !(tolower(response) %in% c("rose", "duck", "pigeon", "rat"))) 

# categprize responses
d_prod_main_responseCat <- d_prod_main_valid %>%
  rowwise() %>%
  mutate( 
    response_cat =
      ifelse(
        # to be extended depending on participants' responses
        tolower(response) %in% c("bird", "birds", "dog", "dogs", "fish","fishes",
                                 "flower", "flowers", "tree", "trees", "animal", "plant", "plants", "one plant", "weed", "weeds"),
        "basic", "sub"),
    resp_cat = ifelse(response_cat == "basic", 1, 0),
    response_label = "basic"
  )
``` 

```{r}
# plot
d_prod_main_responseCat %>%
  group_by(syntax, response_label) %>%
  tidyboot_mean(column = resp_cat) %>% # calculate proportion of basic-level labels in the different conditions 
  ungroup() %>%
  mutate(syntax = factor(syntax, 
                         levels = c("prenominal", "predicative"),
                         labels= c("Predicate NP", "Subject NP"))
  ) %>% 
  ggplot(aes(x = syntax, fill = syntax,
             y = mean, ymin = ci_lower, ymax = ci_upper)) +
  geom_col(position = position_dodge(0.8)) +
  geom_linerange(position = position_dodge(0.8)) +
  labs( y = "Proportion of basic-level responses") +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  ggtitle("The proportion of basic-level responses by syntactic condition")
```

``` {r}
# contrast coding of syntax 
# subject NP -1. predicate NP 1, explicit numeric coding to avoid unpredicted bahaviour due to factors
d_prod_main_responseCat <- d_prod_main_responseCat %>%
  mutate(syntax_num = ifelse( syntax == "prenominal", 0.5, -0.5),
         size = ifelse(size == "big", -1, 1))

```

``` {r lmer}
# exploratory frequentist analysis
lm.prod.fit <- glmer(resp_cat ~ 0 + syntax + (1 + syntax | submission_id) +
                      (1 + syntax | picture), 
                    data = d_prod_main_responseCat, 
                    family = "binomial",
                    REML = F,
                    control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                    )


lm.prod.fit.simple <- glm(resp_cat ~  syntax_num, 
                    data = d_prod_main_responseCat , 
                    family = binomial(link = "identity")
                    )


summary(lm.prod.fit.simple)

head()
contrasts(d_prod_main_responseCat$syntax) <- c(0, 1)
```
```{r}
x <- 0.65*0.5 -0.5
exp(x)/(1 + exp(x))

d_prod_main_responseCat %>%
  group_by(syntax) %>%
  summarize(m = mean(resp_cat))
```

``` {r lmer w size}
# exploratory analysis with the main effect of target size
lm.prod.w.size <- glmer(resp_cat ~ 0 + syntax*size + (1 + syntax*size | submission_id) +
                      (1 + syntax*size | target), 
                    data = d_prod_main_responseCat, 
                    family = "binomial",
                    REML = F,
                    control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5))
                    )
summary(lm.prod.w.size)

head(d_prod_main_responseCat)
```


``` {r brm}
# Bayesian model

# set priors
Prior <- c(set_prior("beta(1,1)", lb=0, ub=1, class = "b")) # prior on random effects

# full model
b.prod.w.prior.dummy.noint <- brm( resp_cat ~  syntax , 
                    data = d_prod_main_responseCat, 
                    family = binomial(link="identity"),
                    prior=Prior,
                    sample_prior = T,
                    control=list(adapt_delta=0.95))
summary(b.prod.w.prior.dummy)
```

``` {r}
# nullhypothesis that proportions of basic-level responses do not differ
h1 <- hypothesis(b.prod.w.prior.dummy, " -syntax =  syntax", class = "b") 

print(h1, digits = 3)

# alternative hypothesis given the posterior compared to the prior
1/h1$hypothesis$Evid.Ratio
```